---
site_name: "Data Science & AI Glossary"
site_url: "https://hogenttin.github.io/dsai-glossary/"
repo_name: "HoGentTIN/dsai-glossary"
repo_url: "https://github.com/HoGentTIN/dsai-glossary"

nav:
  - Inhoud/Content: 'index.md'
  - Nederlands:
      - Index: 'index-nl.md'
      - Notatie: 'nl/notatie.md'
  - English:
      - Index: 'index-en.md'
      - Notation: 'en/notation.md'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

theme:
  name: material
  features:
    - navigation.expand
  logo: "images/icons8-scatter-plot-96.png"
  favicon: "images/icons8-scatter-plot-96-black.png"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

